export const ROUTES = {
  home: '/',
  login: '/login',
  onboardingProfile: '/onboarding/profile',
  onboardingInstagram: '/onboarding/instagram',
  dashboard: '/dashboard',
  automations: '/automations',
  automationNew: '/automations/new',
  automationEdit: (id: string) => `/automations/${id}`,
  messages: '/messages',
  comments: '/comments',
  templates: '/templates',
  analytics: '/analytics',
  instagram: '/instagram',
  iceBreakers: '/ice-breakers',
  settings: '/settings',
  billing: '/billing',
  privacyPolicy: '/privacy',
  dataDeletion: '/data-deletion',
  termsOfService: '/terms',
};
